kind: pipeline
type: docker
name: gravity-data-extractor

trigger:
  branch:
    - master
    - price-version

pipeline:
  publish-data-extractor:
    image: plugins/docker
    dockerfile: ./Dockerfile
    context: .
    repo: gravityhuborg/gravity-data-extractor
    tags: "${DRONE_BRANCH}"
    secrets: [docker_username,docker_password]
    when:
      branch:
        - master
        - price-version

  extractor-deploy:
    image: appleboy/drone-ssh
    host: drone.gravityhub.org
    username: root
    port: 22
    key:
      from_secret: private_key
    envs:
      - drone_branch
    script:
      - branch=${DRONE_BRANCH} && cd /var/www/gravity-node-data-extractor && bash ./rebuild.sh "$branch"
    when:
      branch:
        - master
        - price-version
