kind: pipeline
type: docker
name: gravity-data-extractors

trigger:
  branch:
    - master
    - price-version

pipeline:
  publish-data-extractor:
    image: plugins/docker
    dockerfile: ./Dockerfile
    context: .
    repo: gravityhuborg/gravity-data-extractors
    tags: "${DRONE_BRANCH}"
    secrets: [docker_username,docker_password]
    when:
      branch:
        - master
        - price-version

#  extractors-deploy:
#    image: appleboy/drone-ssh
#    host: drone.gravityhub.org
#    username: root
#    port: 22
#    key:
#      from_secret: private_key
#    script:
#      - branch=${DRONE_BRANCH} && cd /var/www/gravity-node-data-extractors && bash ./rebuild.sh "$branch"
#    when:
#      branch:
#        - master
#        - price-version
